### ISSUE TITLE
Column visibility is not preserved during session.

### ISSUE THREAD

**Issue by ptopa** [aghinz2015/foram#37]
Setting related to column visibility should be preserved within one session. I think it should be saved in account settings. At this moment I lose these setting even when I refresh page.

**Comment by ErykZimonczyk** [comment]
Is it ok to save those settings to localStorage / cookies? It will much much easier to change settings and the only minus is they will be preserved per PC not per user.

**Comment by ptopa** [comment]
Yes, I agree to implement this in such the way.
